### PR TITLE
Hdt rename

### PR DESCRIPTION
**Pull request by adzenith**
Merge two almost-identical arm macro files into one parameterized file.
Rename links and joints to be more descriptive.
Make inertial properties more realistic.

### CODE REVIEW

**Comment by Mishra42** [comment]
OK, so why does this need to be merged today?  I don't think we should get into the habit of merging broken code, it will bite us down the line and we can test from the branch can't we?  This sounds like we're almost there and it can be quickly resolved by sitting down and going through the code together to make sure everything is in the correct coordinate frame and working for everyone.

**Comment by rjgriffin42** [comment]
Because the xacros that make the Escher model in the trec_platforms repo call the xacros located in this repo, which are being renamed in this pull request. The trec_platforms repo _must_ be finished, and I have been saying that for over two weeks now. 

That being said, one time does not make a habit. I had already moved the coordinate frame, had the discussion, was told it was ok, and apparently they got moved back. That does not mean that it is a quick resolution, either, as it will involve quite a bit more work to get everything correct.

**Comment by rjgriffin42** [comment]
In addition, this makes it no more _wrong_ that it was previously, with the completely incorrect inertias. No one said anything was broken, the inertias are just incorrect. As everything else works, just the inertias in the urdf need to be fixed, I am pulling the trigger on this.

**Comment by Mishra42** [comment]
But Can't the TREC_Platforms repo refer to this branch?  I realize this is taking longer than expected to complete, but it's a big pull request that affects multiple systems.  I get the feeling folks for one reason or another may not be on the same page anymore with how to proceed with this.  I understand that it's frustrating, but I'm just trying to minimize the rework for both teams.

**Comment by rjgriffin42** [comment]
The only thing I am referring to is the inertias. That is it. Nothing else pulls the inertia data. This involves no other rework than that. Everything else has been checked by everyone who's system it affects. The only people who were working on it were Nik and I. I am assuming the inertial frames got over looked.

**Pull request merged**
